# Generated by Django 2.2.5 on 2019-11-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191107_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'english'), ('korean', 'korean')], max_length=10),
        ),
    ]
