# Generated by Django 2.2.5 on 2019-11-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20191112_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(help_text='how many people will be staying?'),
        ),
    ]
